version: '3.2'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: suyc
      MYSQL_USER: suyc
      MYSQL_PASSWORD: suyc
      MYSQL_DATABASE: suyc
    ports:
      - "3306:3306"
  frontend:
    build: .
    env_file:
      - local.env
    ports:
      - "3000:3000"
    volumes:
      - .:/suyc
