config:
  project:                mlab-speedup-integration
  dataset:                MLab_Louisville_Data
  email:                  speedup-service-account@mlab-speedup-integration.iam.gserviceaccount.com
  private_key_path:       Mlab-SpeedUp-Integration-bd0a76086c36.p12
  private_key_passphrase: notasecret
  auth_method:            private_key
